# https://jekyllrb.com/docs/configuration/

# site-wide variables
title: The AI Design Lab # title of site, used in tab name and elsewhere
email: pchiang@fudan.edu.cn # default email
google: Patrick Yin Chiang # default name to search on Google Scholar
github: PatrickAIlab # default GitHub user/org, without the @
twitter:  # default Twitter handle, without the @
instagram: "" # default Instagram handle, without the @
youtube: "" # default YouTube channel handle

# base directory where site is hosted
# set to "" if hosting at a custom domain, eg yoursite.com
baseurl: ""

# default front matter parameters for markdown files
# defaults can be overridden on a particular page, eg:
# ---
# description: Description unique to this page
# background: images/different-bg-for-this-page.jpg
# ---
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      description: Where Genome gets compiled # description that will show under search engine results
      background: images/backgrounds/laptop-paper.jpg # background image in header and footer
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from
